name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "percy snapshot -p=5339 ."
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
